# Clase C3 - Numpy

## Temario

- Que es numpy (presentacion)
- ND-Arrays (presentacion)
- Indexing (Ejemplo con presentacion)
- Bradcasting (presentacion)
- Cambiar tipo de datos
- Funciones especificas en el ejemplo final
    - np.genfromtxt()
    - cumprod()
    - enumerate()
    - np.reshape()
    - np.diff()

## Temario extra practica

- Metodos de inicializacion de arrays
- Random (lo vamos a retomar proxima clase)
- Eficiencia de numpy

## Organizacion prevista para la clase de hoy

- Consultas y puesta en comun de dudas o repaso de los temas de la clase pasada (15 mins)
- Presentacion de Numpy con ejemplo (45 mins)
- Hands-On (15-30 mins)
- Ejemplo mas completo (1 h)



In [1]:
# ejemplos de la presentacion

import numpy as np


In [18]:
datos = np.array(['Esto es una frase muy larga, vamos a ver si la acepta',3.0,5,7,10])
print (datos)
datos[1] = 'Esto es '
datos[1:3]

['Esto es una frase muy larga, vamos a ver si la acepta' '3.0' '5' '7'
 '10']


array(['Esto es ', '5'], dtype='<U53')

In [86]:
mat = np.array([[2,3,4],[1,1,1],[0,0,0]])
A = mat[[0,0,0,1,1,2],0]

print (A)
A.ndim


[2 2 2 1 1 0]


1

In [62]:
vec = np.array([1,2,3,4,5,6,7,8,9])

mascara = vec % 3 == 0 

print (mascara)
print (vec[3:-8])

[False False  True False False  True False False  True]
[]


In [65]:
np.arange(13,8,-2)

array([13, 11,  9])

In [78]:
costofijo = np.array([1,3,5,7])
costovariable = np.array([2,4,6,8])
produccion = [203,0,0]

costototal = costofijo + costovariable * produccion
print (costototal)



ValueError: operands could not be broadcast together with shapes (4,) (3,) 

# Hands-On

Ejercicios extra:

- Hacer un codigo que arme los primeros m elementos las tablas de multiplicar de un numero arbitrario N usando broadcasting y np.narray()
    - Leer la documentacion: https://numpy.org/doc/stable/reference/generated/numpy.arange.html

- Hacer una funcion que acepte un entero o una lista de enteros y arme sus tablas de multiplicar hasta el 10
    - Leer la documentacion de reshape https://numpy.org/doc/stable/reference/generated/numpy.reshape.html y https://stackoverflow.com/questions/18691084/what-does-1-mean-in-numpy-reshape

In [88]:
# Soluciones posibles

import numpy as np

m = 5
N = 8
escala = np.arange(1,m+1)
multiplos = escala * N
display (multiplos)


array([ 8, 16, 24, 32, 40])

In [110]:
def tabla1(numeros):
    if type(numeros) == int:
        numeros = [numeros]
    if type(numeros) != list:
        raise ValueError(f'Se espera como argumento un entero o una lista de enteros y se recibio un dato tipo {type(numeros)}')
    return numeros * np.arange(10).reshape(-1,1)
    

In [113]:
try:
    tabla = tabla1('Hola')
except ValueError:
    print ('Fallamos!')


Fallamos!


In [101]:
datos = np.arange(9)
datos = datos.reshape(-1,1)
print (datos)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
